{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.MasayukiSuda",
    "module" : "BubbleLayout",
    "version" : "v1.2.2",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "6.7.1",
      "buildId" : "rratz6mbg5eatgsxycntrbnheq"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "BubbleLayout-v1.2.2.aar",
      "url" : "BubbleLayout-v1.2.2.aar",
      "size" : 23463,
      "sha512" : "0940b523768220c07414ba4fdd3f75bbbcd4ac5bb82d617e1bd4a6f78d9d3b3e53dac3c0591a83b69634b75713a8e1b6d627fcf4858329a8c29f685692be80f6",
      "sha256" : "05581d64af745e9bb47987c7ed68fa934a81a2f890ce77371188e477b2ddeb07",
      "sha1" : "d138ca8ea400bce5d664ab0cce45eabf4e7d7316",
      "md5" : "1cc21408fdc5c4f94429e3666dfb19d5"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.3.0"
      }
    } ],
    "files" : [ {
      "name" : "BubbleLayout-v1.2.2.aar",
      "url" : "BubbleLayout-v1.2.2.aar",
      "size" : 23463,
      "sha512" : "0940b523768220c07414ba4fdd3f75bbbcd4ac5bb82d617e1bd4a6f78d9d3b3e53dac3c0591a83b69634b75713a8e1b6d627fcf4858329a8c29f685692be80f6",
      "sha256" : "05581d64af745e9bb47987c7ed68fa934a81a2f890ce77371188e477b2ddeb07",
      "sha1" : "d138ca8ea400bce5d664ab0cce45eabf4e7d7316",
      "md5" : "1cc21408fdc5c4f94429e3666dfb19d5"
    } ]
  } ]
}